from django.db import models
from authentication.models import User

# Create your models here.


class ReportLog(models.Model):
    class ReportTypes(models.TextChoices):
        GENERAL_MONTHLY = "GM", "General Monthly Report"
        GENERAL_SPECIFIED_PERIOD = "GSP", "General Report on Specified Period"
        STUDENT_HISTORY_ALL_TIME = "SHAT", "General Student History"
        STUDENT_HISTORY_SPECIFIED_PERIOD = "SHSP", "Student Report Specified Period"

    user_id = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="report_created_by"
    )
    date = models.DateTimeField(auto_now_add=True)
    report_type = models.CharField(max_length=4, choices=ReportTypes.choices)

    def __str__(self):
        return f"Report '{self.get_report_type_display()}' generated by {self.user_id.first_name} on {self.date.strftime('%Y-%m-%d %H:%M:%S')}"
