# Generated by Django 5.2 on 2025-08-14 17:57

import django.core.validators
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_by_student_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_cpf',
            field=models.CharField(max_length=11, validators=[utils.validators.validate_cpf, django.core.validators.RegexValidator('^\\d{11}$', message='Invalid CPF. Must contain exactly 11 digits.')]),
        ),
    ]
