# Generated by Django 5.2 on 2025-08-08 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_created_by_student_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEntry',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('notes', models.CharField(db_comment='Additional notes', help_text='Observações adicionais', max_length=500, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('healthpro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_entries_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_entries', to='students.student')),
            ],
        ),
    ]
